version: '3.8'

services:
  browserless:
    image: ghcr.io/browserless/chromium
    ports:
      - "3000:3000"
    networks:
      - automation-net
    restart: unless-stopped
    environment:
      - TOKEN=${BROWSERLESS_API_TOKEN}

  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - automation-net
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - GENERIC_TIMEZONE=${TIMEZONE}
      - WEBHOOK_URL=${WEBHOOK_URL}

networks:
  automation-net:
    driver: bridge

volumes:
  n8n_data:
